services:
  postgres:
    image: postgres:16-alpine
    container_name: revopspulse-postgres
    environment:
      POSTGRES_DB: revopspulse
      POSTGRES_USER: revopspulse
      POSTGRES_PASSWORD: revopspulse
    ports:
      - "5432:5432"
    volumes:
      - revopspulse_postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U revopspulse -d revopspulse"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:3.1.0-python3.12
    container_name: revopspulse-airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://revopspulse:revopspulse@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: revopspulse_local_jwt_secret
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    volumes:
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
               airflow db migrate"

  airflow-webserver:
    image: apache/airflow:3.1.0-python3.12
    container_name: revopspulse-airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://revopspulse:revopspulse@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: revopspulse_local_jwt_secret
      AIRFLOW__API__SECRET_KEY: revopspulse_local_secret_key
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
               airflow api-server"

  airflow-dag-processor:
    image: apache/airflow:3.1.0-python3.12
    container_name: revopspulse-airflow-dag-processor
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://revopspulse:revopspulse@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: revopspulse_local_jwt_secret
      AIRFLOW__API__SECRET_KEY: revopspulse_local_secret_key
    volumes:
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
               airflow dag-processor"


  airflow-scheduler:
    image: apache/airflow:3.1.0-python3.12
    container_name: revopspulse-airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://revopspulse:revopspulse@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/dags
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: revopspulse_local_jwt_secret
      AIRFLOW__API__SECRET_KEY: revopspulse_local_secret_key
    volumes:
      - .:/opt/airflow/project
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
               airflow scheduler"

volumes:
  revopspulse_postgres_data:
